-- ============================================================
-- 008_seed_companies.sql
-- Initial company seed data.
-- FR market is fully populated.
-- EN/DE/ES/IT: top companies seeded, contacts to be researched.
-- ============================================================
-- Add more companies via Supabase Studio or future migrations.
-- Pattern: INSERT INTO companies (name, country_code, category, sort_order, website)

-- ── STREAMING ────────────────────────────────────────────────
insert into companies (name, country_code, category, sort_order, website) values
  ('Netflix',             'fr', 'streaming', 1,  'https://www.netflix.com'),
  ('Disney+',             'fr', 'streaming', 2,  'https://www.disneyplus.com'),
  ('Amazon Prime Video',  'fr', 'streaming', 3,  'https://www.primevideo.com'),
  ('Canal+',              'fr', 'streaming', 4,  'https://www.canalplus.com'),
  ('Apple TV+',           'fr', 'streaming', 5,  'https://tv.apple.com'),
  ('Spotify',             'fr', 'streaming', 6,  'https://www.spotify.com'),
  ('Deezer',              'fr', 'streaming', 7,  'https://www.deezer.com'),
  ('Paramount+',          'fr', 'streaming', 8,  'https://www.paramountplus.com'),
  ('MAX',                 'fr', 'streaming', 9,  'https://www.max.com'),
  ('OCS',                 'fr', 'streaming', 10, 'https://www.ocs.fr'),
  ('Crunchyroll',         'fr', 'streaming', 11, 'https://www.crunchyroll.com'),

  ('Netflix',             'en', 'streaming', 1,  'https://www.netflix.com'),
  ('Disney+',             'en', 'streaming', 2,  'https://www.disneyplus.com'),
  ('Amazon Prime Video',  'en', 'streaming', 3,  'https://www.primevideo.com'),
  ('Apple TV+',           'en', 'streaming', 4,  'https://tv.apple.com'),
  ('Spotify',             'en', 'streaming', 5,  'https://www.spotify.com'),
  ('NOW TV',              'en', 'streaming', 6,  'https://www.nowtv.com'),
  ('BritBox',             'en', 'streaming', 7,  'https://www.britbox.com'),
  ('Paramount+',          'en', 'streaming', 8,  'https://www.paramountplus.com'),
  ('DAZN',                'en', 'streaming', 9,  'https://www.dazn.com'),

  ('Netflix',             'de', 'streaming', 1,  'https://www.netflix.com'),
  ('Disney+',             'de', 'streaming', 2,  'https://www.disneyplus.com'),
  ('Amazon Prime Video',  'de', 'streaming', 3,  'https://www.primevideo.com'),
  ('Apple TV+',           'de', 'streaming', 4,  'https://tv.apple.com'),
  ('Spotify',             'de', 'streaming', 5,  'https://www.spotify.com'),
  ('Joyn+',               'de', 'streaming', 6,  'https://www.joyn.de'),
  ('MagentaTV',           'de', 'streaming', 7,  'https://www.telekom.de/magenta-tv'),
  ('DAZN',                'de', 'streaming', 8,  'https://www.dazn.com'),

  ('Netflix',             'es', 'streaming', 1,  'https://www.netflix.com'),
  ('Disney+',             'es', 'streaming', 2,  'https://www.disneyplus.com'),
  ('Amazon Prime Video',  'es', 'streaming', 3,  'https://www.primevideo.com'),
  ('Apple TV+',           'es', 'streaming', 4,  'https://tv.apple.com'),
  ('Spotify',             'es', 'streaming', 5,  'https://www.spotify.com'),
  ('Filmin',              'es', 'streaming', 6,  'https://www.filmin.es'),
  ('Movistar+',           'es', 'streaming', 7,  'https://ver.movistarplus.es'),
  ('DAZN',                'es', 'streaming', 8,  'https://www.dazn.com'),

  ('Netflix',             'it', 'streaming', 1,  'https://www.netflix.com'),
  ('Disney+',             'it', 'streaming', 2,  'https://www.disneyplus.com'),
  ('Amazon Prime Video',  'it', 'streaming', 3,  'https://www.primevideo.com'),
  ('Apple TV+',           'it', 'streaming', 4,  'https://tv.apple.com'),
  ('Spotify',             'it', 'streaming', 5,  'https://www.spotify.com'),
  ('Paramount+',          'it', 'streaming', 6,  'https://www.paramountplus.com'),
  ('DAZN',                'it', 'streaming', 7,  'https://www.dazn.com'),
  ('Mediaset Infinity',   'it', 'streaming', 8,  'https://www.mediasetinfinity.mediaset.it');

-- ── TELECOM MOBILE ───────────────────────────────────────────
insert into companies (name, country_code, category, sort_order, website) values
  ('Orange',           'fr', 'telecom_mobile', 1, 'https://www.orange.fr'),
  ('SFR',              'fr', 'telecom_mobile', 2, 'https://www.sfr.fr'),
  ('Bouygues Telecom', 'fr', 'telecom_mobile', 3, 'https://www.bouyguestelecom.fr'),
  ('Free Mobile',      'fr', 'telecom_mobile', 4, 'https://mobile.free.fr'),
  ('Coriolis',         'fr', 'telecom_mobile', 5, 'https://www.coriolis.com'),
  ('Prixtel',          'fr', 'telecom_mobile', 6, 'https://www.prixtel.com'),
  ('NRJ Mobile',       'fr', 'telecom_mobile', 7, 'https://www.nrjmobile.fr'),
  ('Auchan Telecom',   'fr', 'telecom_mobile', 8, 'https://www.auchan-telecom.fr'),

  ('EE',            'en', 'telecom_mobile', 1, 'https://www.ee.co.uk'),
  ('O2',            'en', 'telecom_mobile', 2, 'https://www.o2.co.uk'),
  ('Vodafone',      'en', 'telecom_mobile', 3, 'https://www.vodafone.co.uk'),
  ('Three',         'en', 'telecom_mobile', 4, 'https://www.three.co.uk'),
  ('Sky Mobile',    'en', 'telecom_mobile', 5, 'https://www.sky.com/shop/mobile'),
  ('Virgin Mobile', 'en', 'telecom_mobile', 6, 'https://www.virginmobile.com'),
  ('giffgaff',      'en', 'telecom_mobile', 7, 'https://www.giffgaff.com'),
  ('Tesco Mobile',  'en', 'telecom_mobile', 8, 'https://www.tescomobile.com'),

  ('Deutsche Telekom', 'de', 'telecom_mobile', 1, 'https://www.telekom.de'),
  ('Vodafone',         'de', 'telecom_mobile', 2, 'https://www.vodafone.de'),
  ('O2',               'de', 'telecom_mobile', 3, 'https://www.o2online.de'),
  ('1&1',              'de', 'telecom_mobile', 4, 'https://www.1und1.de'),
  ('congstar',         'de', 'telecom_mobile', 5, 'https://www.congstar.de'),
  ('Aldi Talk',        'de', 'telecom_mobile', 6, 'https://www.alditalk.de'),
  ('Lidl Connect',     'de', 'telecom_mobile', 7, 'https://www.lidl.de/lidl-connect'),

  ('Movistar',    'es', 'telecom_mobile', 1, 'https://www.movistar.es'),
  ('Orange',      'es', 'telecom_mobile', 2, 'https://www.orange.es'),
  ('Vodafone',    'es', 'telecom_mobile', 3, 'https://www.vodafone.es'),
  ('Jazztel',     'es', 'telecom_mobile', 4, 'https://www.jazztel.com'),
  ('MásMóvil',    'es', 'telecom_mobile', 5, 'https://www.masmovil.es'),
  ('Yoigo',       'es', 'telecom_mobile', 6, 'https://www.yoigo.com'),
  ('Digi',        'es', 'telecom_mobile', 7, 'https://www.digimobil.es'),
  ('Simyo',       'es', 'telecom_mobile', 8, 'https://www.simyo.es'),

  ('TIM',        'it', 'telecom_mobile', 1, 'https://www.tim.it'),
  ('Vodafone',   'it', 'telecom_mobile', 2, 'https://www.vodafone.it'),
  ('Wind Tre',   'it', 'telecom_mobile', 3, 'https://www.windtre.it'),
  ('Iliad',      'it', 'telecom_mobile', 4, 'https://www.iliad.it'),
  ('PosteMobile','it', 'telecom_mobile', 5, 'https://www.postemobile.it'),
  ('Fastweb',    'it', 'telecom_mobile', 6, 'https://www.fastweb.it'),
  ('CoopVoce',   'it', 'telecom_mobile', 7, 'https://www.coopvoce.it');

-- ── TELECOM INTERNET (BOX) ───────────────────────────────────
insert into companies (name, country_code, category, sort_order, website) values
  ('Orange',           'fr', 'telecom_internet', 1, 'https://www.orange.fr'),
  ('Free',             'fr', 'telecom_internet', 2, 'https://www.free.fr'),
  ('SFR',              'fr', 'telecom_internet', 3, 'https://www.sfr.fr'),
  ('Bouygues Telecom', 'fr', 'telecom_internet', 4, 'https://www.bouyguestelecom.fr'),
  ('RED by SFR',       'fr', 'telecom_internet', 5, 'https://www.red-by-sfr.fr'),
  ('Sosh',             'fr', 'telecom_internet', 6, 'https://www.sosh.fr'),
  ('B&You',            'fr', 'telecom_internet', 7, 'https://www.bouyguestelecom.fr/offres-mobiles/b-and-you'),

  ('BT',           'en', 'telecom_internet', 1, 'https://www.bt.com'),
  ('Sky',          'en', 'telecom_internet', 2, 'https://www.sky.com'),
  ('Virgin Media', 'en', 'telecom_internet', 3, 'https://www.virginmedia.com'),
  ('TalkTalk',     'en', 'telecom_internet', 4, 'https://www.talktalk.co.uk'),
  ('Plusnet',      'en', 'telecom_internet', 5, 'https://www.plus.net'),
  ('EE Broadband', 'en', 'telecom_internet', 6, 'https://www.ee.co.uk/broadband'),
  ('NOW TV',       'en', 'telecom_internet', 7, 'https://www.nowtv.com'),

  ('Deutsche Telekom', 'de', 'telecom_internet', 1, 'https://www.telekom.de'),
  ('Vodafone',         'de', 'telecom_internet', 2, 'https://www.vodafone.de'),
  ('1&1',              'de', 'telecom_internet', 3, 'https://www.1und1.de'),
  ('O2',               'de', 'telecom_internet', 4, 'https://www.o2online.de'),
  ('Freenet',          'de', 'telecom_internet', 5, 'https://www.freenet.de'),

  ('Movistar', 'es', 'telecom_internet', 1, 'https://www.movistar.es'),
  ('Orange',   'es', 'telecom_internet', 2, 'https://www.orange.es'),
  ('Vodafone', 'es', 'telecom_internet', 3, 'https://www.vodafone.es'),
  ('Jazztel',  'es', 'telecom_internet', 4, 'https://www.jazztel.com'),
  ('MásMóvil', 'es', 'telecom_internet', 5, 'https://www.masmovil.es'),
  ('Digi',     'es', 'telecom_internet', 6, 'https://www.digimobil.es'),

  ('TIM',     'it', 'telecom_internet', 1, 'https://www.tim.it'),
  ('Vodafone','it', 'telecom_internet', 2, 'https://www.vodafone.it'),
  ('Wind Tre','it', 'telecom_internet', 3, 'https://www.windtre.it'),
  ('Fastweb', 'it', 'telecom_internet', 4, 'https://www.fastweb.it'),
  ('Iliad',   'it', 'telecom_internet', 5, 'https://www.iliad.it'),
  ('Sky Italia','it', 'telecom_internet', 6, 'https://www.sky.it');

-- ── GYM ──────────────────────────────────────────────────────
insert into companies (name, country_code, category, sort_order, website, aliases) values
  ('Basic-Fit',        'fr', 'gym', 1, 'https://www.basic-fit.com', '{}'),
  ('Fitness Park',     'fr', 'gym', 2, 'https://www.fitness-park.fr', '{}'),
  ('Keep Cool',        'fr', 'gym', 3, 'https://www.keepcool.fr', '{}'),
  ('L''Orange Bleue',  'fr', 'gym', 4, 'https://www.lorangebleue.fr', ARRAY['Orange Bleue']),
  ('Neoness',          'fr', 'gym', 5, 'https://www.neoness.com', '{}'),
  ('Club Med Gym',     'fr', 'gym', 6, 'https://www.clubmedgym.fr', '{}'),
  ('Gofit',            'fr', 'gym', 7, 'https://www.gofit.fr', '{}'),

  ('PureGym',          'en', 'gym', 1, 'https://www.puregym.com', '{}'),
  ('The Gym Group',    'en', 'gym', 2, 'https://www.thegymgroup.com', '{}'),
  ('David Lloyd',      'en', 'gym', 3, 'https://www.davidlloyd.co.uk', '{}'),
  ('Virgin Active',    'en', 'gym', 4, 'https://www.virginactive.co.uk', '{}'),
  ('Anytime Fitness',  'en', 'gym', 5, 'https://www.anytimefitness.co.uk', '{}'),
  ('Basic-Fit',        'en', 'gym', 6, 'https://www.basic-fit.com', '{}'),
  ('JD Gyms',          'en', 'gym', 7, 'https://www.jdgyms.co.uk', '{}'),

  ('McFit',         'de', 'gym', 1, 'https://www.mcfit.com', '{}'),
  ('FitX',          'de', 'gym', 2, 'https://www.fitx.de', '{}'),
  ('John Reed',     'de', 'gym', 3, 'https://www.johnreed.fitness', '{}'),
  ('INJOY',         'de', 'gym', 4, 'https://www.injoy.de', '{}'),
  ('Clever Fit',    'de', 'gym', 5, 'https://www.clever-fit.com', '{}'),
  ('FitnessFirst',  'de', 'gym', 6, 'https://www.fitnessfirst.de', '{}'),
  ('RSG Group',     'de', 'gym', 7, 'https://www.rsg-group.com', '{}'),

  ('Holmes Place',    'es', 'gym', 1, 'https://www.holmesplace.com', '{}'),
  ('Metropolitan',    'es', 'gym', 2, 'https://www.metropolitan.es', '{}'),
  ('VivaGym',         'es', 'gym', 3, 'https://www.vivagym.es', '{}'),
  ('Anytime Fitness', 'es', 'gym', 4, 'https://www.anytimefitness.es', '{}'),
  ('Basic-Fit',       'es', 'gym', 5, 'https://www.basic-fit.com', '{}'),
  ('Supera',          'es', 'gym', 6, 'https://www.supera.es', '{}'),
  ('Go Fit',          'es', 'gym', 7, 'https://www.gofit.es', '{}'),

  ('Virgin Active',    'it', 'gym', 1, 'https://www.virginactive.it', '{}'),
  ('McFit',            'it', 'gym', 2, 'https://www.mcfit.com', '{}'),
  ('Anytime Fitness',  'it', 'gym', 3, 'https://www.anytimefitness.com', '{}'),
  ('Basic-Fit',        'it', 'gym', 4, 'https://www.basic-fit.com', '{}'),
  ('Klab',             'it', 'gym', 5, 'https://www.klab.it', '{}'),
  ('FitnessFirst',     'it', 'gym', 6, 'https://www.fitnessfirst.it', '{}');

-- ── INSURANCE HOME ───────────────────────────────────────────
insert into companies (name, country_code, category, sort_order, website) values
  ('AXA',      'fr', 'insurance_home', 1, 'https://www.axa.fr'),
  ('MAIF',     'fr', 'insurance_home', 2, 'https://www.maif.fr'),
  ('Groupama', 'fr', 'insurance_home', 3, 'https://www.groupama.fr'),
  ('Allianz',  'fr', 'insurance_home', 4, 'https://www.allianz.fr'),
  ('GMF',      'fr', 'insurance_home', 5, 'https://www.gmf.fr'),
  ('MAAF',     'fr', 'insurance_home', 6, 'https://www.maaf.fr'),
  ('Generali', 'fr', 'insurance_home', 7, 'https://www.generali.fr'),
  ('Macif',    'fr', 'insurance_home', 8, 'https://www.macif.fr'),
  ('April',    'fr', 'insurance_home', 9, 'https://www.april.fr'),
  ('Covéa',    'fr', 'insurance_home', 10, 'https://www.covea.com'),

  ('Aviva',      'en', 'insurance_home', 1, 'https://www.aviva.co.uk'),
  ('AXA',        'en', 'insurance_home', 2, 'https://www.axa.co.uk'),
  ('Direct Line','en', 'insurance_home', 3, 'https://www.directline.com'),
  ('Admiral',    'en', 'insurance_home', 4, 'https://www.admiral.com'),
  ('LV=',        'en', 'insurance_home', 5, 'https://www.lv.com'),
  ('Nationwide', 'en', 'insurance_home', 6, 'https://www.nationwide.co.uk'),
  ('Halifax',    'en', 'insurance_home', 7, 'https://www.halifax.co.uk'),
  ('Allianz',    'en', 'insurance_home', 8, 'https://www.allianz.co.uk'),

  ('Allianz',    'de', 'insurance_home', 1, 'https://www.allianz.de'),
  ('AXA',        'de', 'insurance_home', 2, 'https://www.axa.de'),
  ('Generali',   'de', 'insurance_home', 3, 'https://www.generali.de'),
  ('HUK-COBURG', 'de', 'insurance_home', 4, 'https://www.huk.de'),
  ('ERGO',       'de', 'insurance_home', 5, 'https://www.ergo.de'),
  ('Zurich',     'de', 'insurance_home', 6, 'https://www.zurich.de'),
  ('Gothaer',    'de', 'insurance_home', 7, 'https://www.gothaer.de'),
  ('R+V',        'de', 'insurance_home', 8, 'https://www.ruv.de'),

  ('Mapfre',          'es', 'insurance_home', 1, 'https://www.mapfre.es'),
  ('AXA',             'es', 'insurance_home', 2, 'https://www.axa.es'),
  ('Allianz',         'es', 'insurance_home', 3, 'https://www.allianz.es'),
  ('Generali',        'es', 'insurance_home', 4, 'https://www.generali.es'),
  ('Zurich',          'es', 'insurance_home', 5, 'https://www.zurich.es'),
  ('Mutua Madrileña', 'es', 'insurance_home', 6, 'https://www.mutua.es'),
  ('Santalucía',      'es', 'insurance_home', 7, 'https://www.santalucia.es'),

  ('Generali',    'it', 'insurance_home', 1, 'https://www.generali.it'),
  ('UnipolSai',   'it', 'insurance_home', 2, 'https://www.unipolsai.it'),
  ('Allianz',     'it', 'insurance_home', 3, 'https://www.allianz.it'),
  ('AXA',         'it', 'insurance_home', 4, 'https://www.axa.it'),
  ('Zurich',      'it', 'insurance_home', 5, 'https://www.zurich.it'),
  ('Cattolica',   'it', 'insurance_home', 6, 'https://www.cattolica.it'),
  ('Reale Mutua', 'it', 'insurance_home', 7, 'https://www.realemutua.it');

-- ── INSURANCE CAR ────────────────────────────────────────────
insert into companies (name, country_code, category, sort_order, website) values
  ('AXA',               'fr', 'insurance_car', 1, 'https://www.axa.fr'),
  ('MAIF',              'fr', 'insurance_car', 2, 'https://www.maif.fr'),
  ('Groupama',          'fr', 'insurance_car', 3, 'https://www.groupama.fr'),
  ('Allianz',           'fr', 'insurance_car', 4, 'https://www.allianz.fr'),
  ('GMF',               'fr', 'insurance_car', 5, 'https://www.gmf.fr'),
  ('MAAF',              'fr', 'insurance_car', 6, 'https://www.maaf.fr'),
  ('Generali',          'fr', 'insurance_car', 7, 'https://www.generali.fr'),
  ('Macif',             'fr', 'insurance_car', 8, 'https://www.macif.fr'),
  ('April',             'fr', 'insurance_car', 9, 'https://www.april.fr'),
  ('Direct Assurance',  'fr', 'insurance_car', 10, 'https://www.direct-assurance.fr'),

  ('Aviva',           'en', 'insurance_car', 1, 'https://www.aviva.co.uk'),
  ('AXA',             'en', 'insurance_car', 2, 'https://www.axa.co.uk'),
  ('Direct Line',     'en', 'insurance_car', 3, 'https://www.directline.com'),
  ('Admiral',         'en', 'insurance_car', 4, 'https://www.admiral.com'),
  ('LV=',             'en', 'insurance_car', 5, 'https://www.lv.com'),
  ('Churchill',       'en', 'insurance_car', 6, 'https://www.churchill.com'),
  ('Hastings Direct', 'en', 'insurance_car', 7, 'https://www.hastingsdirect.com'),
  ('Allianz',         'en', 'insurance_car', 8, 'https://www.allianz.co.uk'),

  ('Allianz',    'de', 'insurance_car', 1, 'https://www.allianz.de'),
  ('AXA',        'de', 'insurance_car', 2, 'https://www.axa.de'),
  ('HUK-COBURG', 'de', 'insurance_car', 3, 'https://www.huk.de'),
  ('ADAC',       'de', 'insurance_car', 4, 'https://www.adac.de'),
  ('ERGO',       'de', 'insurance_car', 5, 'https://www.ergo.de'),
  ('Zurich',     'de', 'insurance_car', 6, 'https://www.zurich.de'),
  ('Gothaer',    'de', 'insurance_car', 7, 'https://www.gothaer.de'),

  ('Mapfre',          'es', 'insurance_car', 1, 'https://www.mapfre.es'),
  ('Mutua Madrileña', 'es', 'insurance_car', 2, 'https://www.mutua.es'),
  ('AXA',             'es', 'insurance_car', 3, 'https://www.axa.es'),
  ('Allianz',         'es', 'insurance_car', 4, 'https://www.allianz.es'),
  ('Generali',        'es', 'insurance_car', 5, 'https://www.generali.es'),
  ('Zurich',          'es', 'insurance_car', 6, 'https://www.zurich.es'),
  ('Direct Seguros',  'es', 'insurance_car', 7, 'https://www.directseguros.es'),

  ('Generali',    'it', 'insurance_car', 1, 'https://www.generali.it'),
  ('UnipolSai',   'it', 'insurance_car', 2, 'https://www.unipolsai.it'),
  ('Allianz',     'it', 'insurance_car', 3, 'https://www.allianz.it'),
  ('AXA',         'it', 'insurance_car', 4, 'https://www.axa.it'),
  ('Zurich',      'it', 'insurance_car', 5, 'https://www.zurich.it'),
  ('Cattolica',   'it', 'insurance_car', 6, 'https://www.cattolica.it'),
  ('Reale Mutua', 'it', 'insurance_car', 7, 'https://www.realemutua.it');

-- ── HEALTH INSURANCE (MUTUELLE) ──────────────────────────────
insert into companies (name, country_code, category, sort_order, website) values
  ('Harmonie Mutuelle', 'fr', 'health_insurance', 1, 'https://www.harmonie-mutuelle.fr'),
  ('Malakoff Humanis',  'fr', 'health_insurance', 2, 'https://www.malakoffhumanis.com'),
  ('Alan',              'fr', 'health_insurance', 3, 'https://alan.com'),
  ('MAIF Santé',        'fr', 'health_insurance', 4, 'https://www.maif.fr'),
  ('April Santé',       'fr', 'health_insurance', 5, 'https://www.april.fr'),
  ('AXA Santé',         'fr', 'health_insurance', 6, 'https://www.axa.fr'),
  ('Henner',            'fr', 'health_insurance', 7, 'https://www.henner.com'),
  ('Mutex',             'fr', 'health_insurance', 8, 'https://www.mutex.fr'),

  ('BUPA',          'en', 'health_insurance', 1, 'https://www.bupa.co.uk'),
  ('AXA Health',    'en', 'health_insurance', 2, 'https://www.axahealth.co.uk'),
  ('Vitality',      'en', 'health_insurance', 3, 'https://www.vitality.co.uk'),
  ('Aviva',         'en', 'health_insurance', 4, 'https://www.aviva.co.uk'),
  ('Cigna',         'en', 'health_insurance', 5, 'https://www.cigna.co.uk'),
  ('Simply Health', 'en', 'health_insurance', 6, 'https://www.simplyhealth.co.uk'),
  ('WPA',           'en', 'health_insurance', 7, 'https://www.wpa.org.uk'),

  ('TK',                  'de', 'health_insurance', 1, 'https://www.tk.de'),
  ('AOK',                 'de', 'health_insurance', 2, 'https://www.aok.de'),
  ('Barmer',              'de', 'health_insurance', 3, 'https://www.barmer.de'),
  ('DAK',                 'de', 'health_insurance', 4, 'https://www.dak.de'),
  ('KKH',                 'de', 'health_insurance', 5, 'https://www.kkh.de'),
  ('IKK',                 'de', 'health_insurance', 6, 'https://www.ikk.de'),
  ('Allianz Gesundheit',  'de', 'health_insurance', 7, 'https://www.allianz.de'),

  ('Sanitas',     'es', 'health_insurance', 1, 'https://www.sanitas.es'),
  ('Adeslas',     'es', 'health_insurance', 2, 'https://www.adeslas.es'),
  ('Asisa',       'es', 'health_insurance', 3, 'https://www.asisa.es'),
  ('Mapfre Salud','es', 'health_insurance', 4, 'https://www.mapfre.es'),
  ('AXA Salud',   'es', 'health_insurance', 5, 'https://www.axa.es'),
  ('DKV',         'es', 'health_insurance', 6, 'https://www.dkvseguros.com'),

  ('UniSalute',    'it', 'health_insurance', 1, 'https://www.unisalute.it'),
  ('Generali',     'it', 'health_insurance', 2, 'https://www.generali.it'),
  ('Blue Assistance','it','health_insurance', 3, 'https://www.blueassistance.it'),
  ('Previmedical', 'it', 'health_insurance', 4, 'https://www.previmedical.it'),
  ('Filo Diretto', 'it', 'health_insurance', 5, 'https://www.filodirektto.it');

-- ── BANK ─────────────────────────────────────────────────────
insert into companies (name, country_code, category, sort_order, website) values
  ('BNP Paribas',       'fr', 'bank', 1,  'https://www.bnpparibas.fr'),
  ('Société Générale',  'fr', 'bank', 2,  'https://www.societegenerale.fr'),
  ('Crédit Agricole',   'fr', 'bank', 3,  'https://www.credit-agricole.fr'),
  ('LCL',               'fr', 'bank', 4,  'https://www.lcl.fr'),
  ('Caisse d''Épargne', 'fr', 'bank', 5,  'https://www.caisse-epargne.fr'),
  ('Banque Populaire',  'fr', 'bank', 6,  'https://www.banquepopulaire.fr'),
  ('La Banque Postale', 'fr', 'bank', 7,  'https://www.labanquepostale.fr'),
  ('Boursorama',        'fr', 'bank', 8,  'https://www.boursorama.com'),
  ('N26',               'fr', 'bank', 9,  'https://www.n26.com'),
  ('Revolut',           'fr', 'bank', 10, 'https://www.revolut.com'),

  ('Barclays',   'en', 'bank', 1, 'https://www.barclays.co.uk'),
  ('HSBC',       'en', 'bank', 2, 'https://www.hsbc.co.uk'),
  ('Lloyds',     'en', 'bank', 3, 'https://www.lloydsbank.com'),
  ('NatWest',    'en', 'bank', 4, 'https://www.natwest.com'),
  ('Santander',  'en', 'bank', 5, 'https://www.santander.co.uk'),
  ('Halifax',    'en', 'bank', 6, 'https://www.halifax.co.uk'),
  ('Monzo',      'en', 'bank', 7, 'https://www.monzo.com'),
  ('Starling',   'en', 'bank', 8, 'https://www.starlingbank.com'),
  ('Revolut',    'en', 'bank', 9, 'https://www.revolut.com'),
  ('Nationwide', 'en', 'bank', 10,'https://www.nationwide.co.uk'),

  ('Deutsche Bank', 'de', 'bank', 1, 'https://www.deutschebank.de'),
  ('Commerzbank',   'de', 'bank', 2, 'https://www.commerzbank.de'),
  ('Sparkasse',     'de', 'bank', 3, 'https://www.sparkasse.de'),
  ('DKB',           'de', 'bank', 4, 'https://www.dkb.de'),
  ('ING',           'de', 'bank', 5, 'https://www.ing.de'),
  ('Comdirect',     'de', 'bank', 6, 'https://www.comdirect.de'),
  ('N26',           'de', 'bank', 7, 'https://www.n26.com'),
  ('Revolut',       'de', 'bank', 8, 'https://www.revolut.com'),

  ('BBVA',      'es', 'bank', 1, 'https://www.bbva.es'),
  ('Santander', 'es', 'bank', 2, 'https://www.bancosantander.es'),
  ('CaixaBank', 'es', 'bank', 3, 'https://www.caixabank.es'),
  ('Bankinter', 'es', 'bank', 4, 'https://www.bankinter.com'),
  ('Sabadell',  'es', 'bank', 5, 'https://www.bancsabadell.com'),
  ('ING España','es', 'bank', 6, 'https://www.ing.es'),
  ('Openbank',  'es', 'bank', 7, 'https://www.openbank.es'),
  ('N26',       'es', 'bank', 8, 'https://www.n26.com'),

  ('Intesa Sanpaolo', 'it', 'bank', 1, 'https://www.intesasanpaolo.com'),
  ('UniCredit',       'it', 'bank', 2, 'https://www.unicredit.it'),
  ('Banco BPM',       'it', 'bank', 3, 'https://www.bancobpm.it'),
  ('Mediolanum',      'it', 'bank', 4, 'https://www.bancamediolanum.it'),
  ('Fineco',          'it', 'bank', 5, 'https://www.finecobank.com'),
  ('N26',             'it', 'bank', 6, 'https://www.n26.com'),
  ('Revolut',         'it', 'bank', 7, 'https://www.revolut.com');

-- ── TRANSPORT ────────────────────────────────────────────────
insert into companies (name, country_code, category, sort_order, website) values
  ('SNCF',       'fr', 'transport', 1, 'https://www.sncf.com'),
  ('Air France', 'fr', 'transport', 2, 'https://www.airfrance.fr'),
  ('Transavia',  'fr', 'transport', 3, 'https://www.transavia.com'),
  ('Vueling',    'fr', 'transport', 4, 'https://www.vueling.com'),
  ('EasyJet',    'fr', 'transport', 5, 'https://www.easyjet.com'),
  ('Ryanair',    'fr', 'transport', 6, 'https://www.ryanair.com'),
  ('RATP',       'fr', 'transport', 7, 'https://www.ratp.fr'),
  ('Flixbus',    'fr', 'transport', 8, 'https://www.flixbus.fr'),
  ('BlaBlaCar',  'fr', 'transport', 9, 'https://www.blablacar.fr'),

  ('National Rail',    'en', 'transport', 1, 'https://www.nationalrail.co.uk'),
  ('British Airways',  'en', 'transport', 2, 'https://www.britishairways.com'),
  ('EasyJet',          'en', 'transport', 3, 'https://www.easyjet.com'),
  ('Ryanair',          'en', 'transport', 4, 'https://www.ryanair.com'),
  ('Virgin Atlantic',  'en', 'transport', 5, 'https://www.virginatlantic.com'),
  ('Trainline',        'en', 'transport', 6, 'https://www.thetrainline.com'),
  ('Flixbus',          'en', 'transport', 7, 'https://www.flixbus.co.uk'),
  ('Eurostar',         'en', 'transport', 8, 'https://www.eurostar.com'),

  ('Deutsche Bahn', 'de', 'transport', 1, 'https://www.bahn.de'),
  ('Lufthansa',     'de', 'transport', 2, 'https://www.lufthansa.com'),
  ('Eurowings',     'de', 'transport', 3, 'https://www.eurowings.com'),
  ('Ryanair',       'de', 'transport', 4, 'https://www.ryanair.com'),
  ('EasyJet',       'de', 'transport', 5, 'https://www.easyjet.com'),
  ('Flixbus',       'de', 'transport', 6, 'https://www.flixbus.de'),

  ('Renfe',   'es', 'transport', 1, 'https://www.renfe.com'),
  ('Iberia',  'es', 'transport', 2, 'https://www.iberia.com'),
  ('Vueling', 'es', 'transport', 3, 'https://www.vueling.com'),
  ('Ryanair', 'es', 'transport', 4, 'https://www.ryanair.com'),
  ('EasyJet', 'es', 'transport', 5, 'https://www.easyjet.com'),
  ('Alsa',    'es', 'transport', 6, 'https://www.alsa.es'),
  ('Avlo',    'es', 'transport', 7, 'https://www.avlorenfe.com'),
  ('Flixbus', 'es', 'transport', 8, 'https://www.flixbus.es'),

  ('Trenitalia',  'it', 'transport', 1, 'https://www.trenitalia.com'),
  ('Italo',       'it', 'transport', 2, 'https://www.italotreno.it'),
  ('ITA Airways', 'it', 'transport', 3, 'https://www.ita-airways.com'),
  ('Ryanair',     'it', 'transport', 4, 'https://www.ryanair.com'),
  ('EasyJet',     'it', 'transport', 5, 'https://www.easyjet.com'),
  ('Vueling',     'it', 'transport', 6, 'https://www.vueling.com'),
  ('Flixbus',     'it', 'transport', 7, 'https://www.flixbus.it');

-- ── LOGISTICS (PARCELS) ──────────────────────────────────────
insert into companies (name, country_code, category, sort_order, website) values
  ('Amazon',              'fr', 'logistics', 1, 'https://www.amazon.fr'),
  ('Cdiscount',           'fr', 'logistics', 2, 'https://www.cdiscount.com'),
  ('Vinted',              'fr', 'logistics', 3, 'https://www.vinted.fr'),
  ('Leboncoin',           'fr', 'logistics', 4, 'https://www.leboncoin.fr'),
  ('La Poste / Colissimo','fr', 'logistics', 5, 'https://www.laposte.fr'),
  ('Chronopost',          'fr', 'logistics', 6, 'https://www.chronopost.fr'),
  ('DHL',                 'fr', 'logistics', 7, 'https://www.dhl.fr'),
  ('UPS',                 'fr', 'logistics', 8, 'https://www.ups.com'),
  ('DPD',                 'fr', 'logistics', 9, 'https://www.dpd.fr'),
  ('GLS',                 'fr', 'logistics', 10,'https://gls-group.com'),

  ('Amazon',      'en', 'logistics', 1, 'https://www.amazon.co.uk'),
  ('eBay',        'en', 'logistics', 2, 'https://www.ebay.co.uk'),
  ('ASOS',        'en', 'logistics', 3, 'https://www.asos.com'),
  ('Royal Mail',  'en', 'logistics', 4, 'https://www.royalmail.com'),
  ('Evri',        'en', 'logistics', 5, 'https://www.evri.com'),
  ('DHL',         'en', 'logistics', 6, 'https://www.dhl.co.uk'),
  ('DPD',         'en', 'logistics', 7, 'https://www.dpd.co.uk'),
  ('UPS',         'en', 'logistics', 8, 'https://www.ups.com'),
  ('FedEx',       'en', 'logistics', 9, 'https://www.fedex.com'),
  ('Yodel',       'en', 'logistics', 10,'https://www.yodel.co.uk'),

  ('Amazon',  'de', 'logistics', 1, 'https://www.amazon.de'),
  ('Otto',    'de', 'logistics', 2, 'https://www.otto.de'),
  ('Zalando', 'de', 'logistics', 3, 'https://www.zalando.de'),
  ('DHL',     'de', 'logistics', 4, 'https://www.dhl.de'),
  ('Hermes',  'de', 'logistics', 5, 'https://www.myhermes.de'),
  ('DPD',     'de', 'logistics', 6, 'https://www.dpd.de'),
  ('UPS',     'de', 'logistics', 7, 'https://www.ups.com'),
  ('FedEx',   'de', 'logistics', 8, 'https://www.fedex.com'),
  ('GLS',     'de', 'logistics', 9, 'https://gls-group.com'),

  ('Amazon',          'es', 'logistics', 1, 'https://www.amazon.es'),
  ('El Corte Inglés', 'es', 'logistics', 2, 'https://www.elcorteingles.es'),
  ('Zara',            'es', 'logistics', 3, 'https://www.zara.com'),
  ('Correos',         'es', 'logistics', 4, 'https://www.correos.es'),
  ('DHL',             'es', 'logistics', 5, 'https://www.dhl.es'),
  ('SEUR',            'es', 'logistics', 6, 'https://www.seur.com'),
  ('MRW',             'es', 'logistics', 7, 'https://www.mrw.es'),
  ('GLS',             'es', 'logistics', 8, 'https://gls-group.com'),

  ('Amazon',           'it', 'logistics', 1, 'https://www.amazon.it'),
  ('eBay',             'it', 'logistics', 2, 'https://www.ebay.it'),
  ('Vinted',           'it', 'logistics', 3, 'https://www.vinted.it'),
  ('Poste Italiane',   'it', 'logistics', 4, 'https://www.poste.it'),
  ('DHL',              'it', 'logistics', 5, 'https://www.dhl.it'),
  ('BRT',              'it', 'logistics', 6, 'https://www.brt.it'),
  ('GLS',              'it', 'logistics', 7, 'https://gls-group.com'),
  ('SDA',              'it', 'logistics', 8, 'https://www.sda.it');

-- Set aliases that couldn't be inlined above (column mismatch in bulk insert)
update companies set aliases = ARRAY['La Poste', 'Colissimo']
where name = 'La Poste / Colissimo' and country_code = 'fr' and category = 'logistics';
